/* MainWindow.java */

// CHECKSTYLE:OFF

package battlebots;

import battlebots.filedroplist.FileDropList;
import battlebots.tools.FileArray;
import battlebots.tools.MainTools;
import battlebots.tools.MemoryFile;
import battlebots.tools.ProcessPipe;
import battlebots.tools.TokenArray;

import filedrop.FileDrop;

import java.awt.EventQueue;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Class for main window.
 *
 * @author Adakite Systems
 * @author adakitesystems@gmail.com
 */
public class MainWindow extends JFrame {

  private static final Logger LOGGER =
      Logger.getLogger(MainWindow.class.getName());

  private static MainWindow _mainWindow;

  /**
   * Creates new form MainWindow.
   */
  /* Changed from public to private. */
  private MainWindow() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the NetBeans Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scrollPaneFileDrop = new javax.swing.JScrollPane();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setText("jButton1");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(103, 103, 103)
            .addComponent(scrollPaneFileDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(137, 137, 137)
            .addComponent(jButton1)))
        .addContainerGap(104, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(scrollPaneFileDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(28, 28, 28))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    /* Debugging button. */
    FileArray files = FileDropList.getFiles();
    if (files == null)
      return;
    int len = files.size();
    for (int i = 0; i < len; i++)
    {
      System.out.println(FileArray.getShortPath(files.get(i)));
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * Main function called when main window is displayed.
   *
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel if available. */
    try {
      for (UIManager.LookAndFeelInfo info :
          UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException
        | InstantiationException
        | IllegalAccessException
        | UnsupportedLookAndFeelException ex) {
      LOGGER.log(Level.SEVERE, null, ex);
    }

    /* Create and display the form. */
    _mainWindow = new MainWindow();
    EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        _mainWindow.setTitle("Battlebots");
        _mainWindow.setResizable(false);
        _mainWindow.setLocationRelativeTo(null);
        _mainWindow.setVisible(true);
      }
    });

    /*
     * Add FileDrop Listener. All valid dropped files are added to the
     * static container object named FileDropList.
     */
    FileDrop fileDrop = new FileDrop(
        _mainWindow.scrollPaneFileDrop,
        new FileDrop.Listener() {
          @Override
          public void filesDropped(File[] files) {
            FileArray droppedFiles = FileDropList.getFiles();
            for (File file : files) {
              droppedFiles.add(file);
            }
          }
    });

    /* DEBUGGING --- start */
//    ArrayList<String> argsList = new ArrayList<>();
//    argsList.add("a");
//    argsList.add("b");
//    argsList.add("c");
//    argsList.add("d");
//    Object[] argsArray = argsList.toArray();
//    String[] argsArrayArray = (String[])argsArray;
//    int len = argsArray.length;
//    for (int i = 0; i < len; i++)
//    {
//      System.out.println(argsArray[i]);
//    }
//    ProcessBuilder p = new ProcessBuilder(argsArrayArray);
//    p.start();



//    ProcessPipe pipe = new ProcessPipe();
//    String path = "bwheadless_newer.exe";
//    TokenArray pipeArgs = new TokenArray();
////    pipeArgs.add("-e \"S:\\install\\StarCraft\\StarCraft.exe\"");
//    pipeArgs.add("-e");
//    pipeArgs.add("\"S:\\install\\StarCraft\\StarCraft.exe\"");
//    pipeArgs.add("-j");
////    pipeArgs.add("-n IronBot");
//    pipeArgs.add("-n");
//    pipeArgs.add("IronBot");
////    pipeArgs.add("-r Terran");
//    pipeArgs.add("-r");
//    pipeArgs.add("Terran");
////    pipeArgs.add("-l BWAPI.dll");
//    pipeArgs.add("-l");
//    pipeArgs.add("BWAPI.dll");
//    pipeArgs.add("--lan");
////    pipeArgs.add("--installpath \"S:\\install\\StarCraft\"");
//    pipeArgs.add("--installpath");
//    pipeArgs.add("\"S:\\install\\StarCraft\"");
//    if (!pipe.open(path, pipeArgs.toStringArray())) {
//      System.out.println("error opening pipe");
//    }
//    System.out.println(path + " " + pipeArgs.toString());



    MemoryFile mf = new MemoryFile();
    mf.readIntoMemory("bwapi.ini");
//    int index = mf.getIndexStartsWith("ai");
//    String newDll;
//    String tmpLine;
//    TokenArray ta = new TokenArray();
//    if (index >= 0) {
//      System.out.println(mf.getLines().get(index));
//      tmpLine = mf.getLines().get(index);
//      newDll = tmpLine.substring(tmpLine.indexOf("=") + 2, tmpLine.length());
//      newDll = MainTools.getParentDirectory(newDll) + "\\NewBot.dll";
//      System.out.println("ai = " + newDll);
////      mf.writeToDisk(mf.getPath());
//    }
    mf.printToConsole();
    /* DEBUGGING --- end */
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JScrollPane scrollPaneFileDrop;
  // End of variables declaration//GEN-END:variables

}
