package droplauncher.mvc;



import droplauncher.util.Constants;
import java.awt.EventQueue;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;



public class MainWindow extends JFrame {



  private static final Logger LOGGER = Logger.getLogger(MainWindow.class.getName());
  private static final boolean CLASS_DEBUG = (Constants.DEBUG && true);



  private Model model;



  public MainWindow() {
    initComponents();

    this.model = new Model();
    this.model.setView(this);
  }



  /* ************************************************************ */
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor in NetBeans.
   */
  /* ************************************************************ */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnTest = new javax.swing.JButton();
    txtDisplay = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnTest.setText("Test");
    btnTest.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTestActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(130, 130, 130)
            .addComponent(btnTest))
          .addGroup(layout.createSequentialGroup()
            .addGap(93, 93, 93)
            .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(150, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(72, 72, 72)
        .addComponent(btnTest)
        .addGap(32, 32, 32)
        .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(131, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  /* ************************************************************ */



  /* ************************************************************ */
  /* View events passed to the Model */
  /* ************************************************************ */

  private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
    this.model.btnTestPressed(evt);
  }//GEN-LAST:event_btnTestActionPerformed

  /* ************************************************************ */



  /* ************************************************************ */
  /* View functions called by the Model */
  /* ************************************************************ */

  public void txtDisplaySetText(String str) {
    txtDisplay.setText(str);
  }

  /* ************************************************************ */



  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (Exception ex) {
      if (CLASS_DEBUG) {
        LOGGER.log(Constants.DEFAULT_LOG_LEVEL, null, ex);
      }
    }

    /* Create and display the form */
    EventQueue.invokeLater(new Runnable() {
      public void run() {
        MainWindow mainWindow = new MainWindow();
        mainWindow.setTitle(Constants.PROGRAM_NAME);
        mainWindow.setResizable(false);
        mainWindow.setLocationRelativeTo(null);
        mainWindow.setVisible(true);
      }
    });
  }



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnTest;
  private javax.swing.JTextField txtDisplay;
  // End of variables declaration//GEN-END:variables



}
